### ISSUE TITLE
Error in dap1[1, j]: incorrect number of dimensions

### ISSUE THREAD

**Issue by carbocation** [cran/APtools#1]
Running `CompareAP` with either the bootstrap or the perturbation approach yields this error, regardless of data set size for me.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by carbocation** [comment]
Thanks, understood. For the record (or perhaps for future searchers), a colleague pointed out that as long as at least 2 timepoints are requested, this doesn't happen. This might point to an indexing bug (e.g., failing to use , `drop=FALSE`) but I haven't looked into it. I did email the author at the DESCRIPTION you pointed out. I will close this issue since you mentioned this is a read-only mirror.
